# -*- coding: utf-8 -*-
"""Wordcloud-GP02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQL4hNBGuL_bPFuWDVMtxJjTtwpg6ZAn
"""

# exercice 1
# author Adeel Hayat
# state : ongoing

# exercice 2
# author Luc Lagoin
# state : ongoing

# exercice 3
# author Nitika Goyal
# state : ongoing

# exercice 4
# author Nathan
# state : ongoing